### ISSUE TITLE
Installation of numpy-stl

### ISSUE THREAD

**Issue by jaskarangrover92** [WoLpH/numpy-stl#103]
Hi, I am getting the following error while installing numpy-stl using pip install. Any suggestions would be helpful:

Collecting numpy-stl
  Using cached https://files.pythonhosted.org/packages/a2/08/19caa3c20fd9a486a0a603e329b22578aca7e6f184f0575fcd0980ba3ac5/numpy-stl-2.10.1.tar.gz
    Complete output from command python setup.py egg_info:
    WARNING
    Cython and Numpy is required for building extension.
    Falling back to pure Python implementation.
    Download error on https://pypi.org/simple/pytest-runner/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645) -- Some packages may not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    Download error on https://pypi.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645) -- Some packages may not be found!
    No local packages or working download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/b0/lv4f1rzd4vb9cz1r8582__1r0000gn/T/pip-install-ogd33n7v/numpy-stl/setup.py", line 132, in <module>
        **setup_kwargs
      File "/Users/jaskaran/Desktop/multiagent/try1/lib/python3.5/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/Users/jaskaran/Desktop/multiagent/try1/lib/python3.5/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Users/jaskaran/Desktop/multiagent/try1/lib/python3.5/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/jaskaran/Desktop/multiagent/try1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/Users/jaskaran/Desktop/multiagent/try1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/Users/jaskaran/Desktop/multiagent/try1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/Users/jaskaran/Desktop/multiagent/try1/lib/python3.5/site-packages/setuptools/dist.py", line 784, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/jaskaran/Desktop/multiagent/try1/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/b0/lv4f1rzd4vb9cz1r8582__1r0000gn/T/pip-install-ogd33n7v/numpy-stl/

**Comment by tomyferra** [comment]
I installed it with pip install numpy-stl

**Comment by WoLpH** [comment]
I've removed the `pytest-runner` dependency from the `setup.py` script. It shouldn't be required in any case.

As for the error you're receiveing, I'm not entirely sure what's causing it. My guess would be an out of date version of setuptools. Try `pip install -U setuptools wheel pip`
