### ISSUE TITLE
pip install numpy-stl fails with python v3.4+

### ISSUE THREAD

**Issue by mamrehn** [WoLpH/numpy-stl#17]
The enum34 requirement in [setup.py](https://github.com/WoLpH/numpy-stl/blob/96cf7373b0960995084ff1b646862b35723f9041/setup.py#L49)'s `install_requires` list induces an error during installation with pip for python versions 3.4 and higher.

More info about enum34: [enum34-incompatible-with-python-35](https://bitbucket.org/stoneleaf/enum34/issues/5/enum34-incompatible-with-python-35).
Is there a way to import enum34 depending on the python version used instead?

Error log:
```bash
$ pip install numpy-stl
Collecting numpy-stl
  Using cached numpy-stl-1.7.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): numpy in ./miniconda3/envs/testenv/lib/python3.5/site-packages (from numpy-stl)
Collecting nine (from numpy-stl)
  Using cached nine-0.3.4.tar.gz
Collecting enum34 (from numpy-stl)
  Using cached enum34-1.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-build-27fj2ir5/enum34/enum/__init__.py", line 371, in __getattr__
        return cls._member_map_[name]
    KeyError: '_convert'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      [...]
      File "/home/username/miniconda3/envs/testenv/lib/python3.5/socket.py", line 73, in <module>
        IntEnum._convert(
      File "/tmp/pip-build-27fj2ir5/enum34/enum/__init__.py", line 373, in __getattr__
        raise AttributeError(name)
    AttributeError: _convert

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-27fj2ir5/enum34
```

**Comment by WoLpH** [comment]
The last release should have fixed it.

Travis, at least, indicates it works on Python 3.5 now: https://travis-ci.org/WoLpH/numpy-stl
