### ISSUE TITLE
AttributeError: module 'stl' has no attribute 'BaseStl

### ISSUE THREAD

**Issue by Adarsh2425** [wolph/numpy-stl#215]
Adarsh2425 ➜ /workspaces/Slicer-for-multi-toolhead-application (main) $ /home/codespace/.python/current/bin/python3 /workspaces/Slicer-for-multi-toolhead-application/imex_slicer.py
Traceback (most recent call last):
  File "/workspaces/Slicer-for-multi-toolhead-application/imex_slicer.py", line 15, in <module>
    from stl import mesh
  File "/home/codespace/.python/current/lib/python3.10/site-packages/stl/mesh.py", line 4, in <module>
    class mesh(stl.BaseStl):
AttributeError: module 'stl' has no attribute 'BaseStl

i dont know what to do now

**Comment by wolph** [comment]
In most cases this is because a conflict with the `stl` package.
Take a look at this issue for more info: https://github.com/wolph/numpy-stl/issues/55#issuecomment-307599781
